import React, { useState } from "react";
import GlobalStyle from "styles/global-style";
import Head from "next/head";
import { Hydrate, QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";
import { RecoilRoot } from "recoil";
import usePageLoading from "hooks/usePageLoading";
import GlobalSpinner from "@/component/global-spinner";
import Toast from "@/component/toast";

const App = ({ Component, pageProps }) => {
  const [queryClient] = useState(() => new QueryClient());
  const loading = usePageLoading();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GlobalStyle />

      <QueryClientProvider client={queryClient}>
        <Hydrate state={pageProps.dehydratedState}>
          <RecoilRoot>
            {loading ? (
              <GlobalSpinner
                width={18}
                height={18}
                marginRight={18}
                dotColor="#8536FF"
              />
            ) : (
              <>
                <Toast />
                <Component {...pageProps} />
              </>
            )}
          </RecoilRoot>
        </Hydrate>

        <ReactQueryDevtools initialIsOpen={false} position="bottom-right" />
      </QueryClientProvider>
    </>
  );
};

export default App;
